version: "3"
services:
    web:
        build: .
        ports:
            - "80:80"
        expose:
            - "80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Accenture123"
            ACCEPT_EULA: "Y"
